name: Deploy to Heroku

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: ${{ secrets.DOCKER_PASSWORD }} && ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker image from Docker Hub
        run: |
          docker pull docker.io/naabda92/log8100_tp2:latest

      - name: Login to Heroku Container Registry
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Tag and Push Docker image to Heroku
        run: |
          docker tag docker.io/naabda92/log8100_tp2:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release the Docker image on Heroku
        run: |
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}